### ISSUE TITLE
Crear componente global llamado Padding

### ISSUE THREAD

**Issue by ngLuis** [ngLuis/easylife__SITE#5]
Los paddings tendrán que tener las siguientes caracterísitcas:

g-padding (pondrá los 4 padding a la vez tanto top, bottom, left y right)
g-padding--xs

g-padding--vertical-xs (Modificará el top y el bottom)
g-padding--horizontal-xs (Modificará el left y el right)

g-padding--left-xs
g-padding--right-xs
g-padding--top-xs
g-padding--bottom-xs

**Comment by ivanrepiso11** [comment]
Hacer mixins para no hacer los paddings globales. Probar a hacer los mixins para cada componente de padding

**Comment by ivanrepiso11** [comment]
Terminado
